[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "John Chanthy", email = "john.chanthy@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.142.2",
    "google-genai>=2.25.0",
    "pdfplumber>=0.11.10",
    "pillow>=12.3.0",
    "pydantic>=2.13.5",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "python-docx>=1.2.0",
    "python-dotenv>=1.2.3",
    "python-multipart>=0.0.32",
    "python-pptx>=1.0.2",
    "reportlab>=5.0.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
